<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icons\edittext3.ico</ApplicationIcon>
    <Version>1.0.1</Version>
    <Company>Radish</Company>
    <Product>Radish Notepad</Product>
    <Copyright>© 2026 Radish</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icons\close.png" />
    <None Remove="icons\copy.png" />
    <None Remove="icons\cut.png" />
    <None Remove="icons\delete.png" />
    <None Remove="icons\find.png" />
    <None Remove="icons\new.png" />
    <None Remove="icons\notepad.ico" />
    <None Remove="icons\open.png" />
    <None Remove="icons\paste.png" />
    <None Remove="icons\print.png" />
    <None Remove="icons\redo.png" />
    <None Remove="icons\replace.png" />
    <None Remove="icons\save.png" />
    <None Remove="icons\saveall.png" />
    <None Remove="icons\selectall.png" />
    <None Remove="icons\undo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icons\edittext3.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icons\close.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\copy.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\cut.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\delete.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\find.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\new.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\notepad.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\open.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\paste.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\print.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\redo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\replace.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\save.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\saveall.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\selectall.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="icons\undo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="images\" />
  </ItemGroup>

</Project>
